### ISSUE TITLE
file.extname doesn't work

### ISSUE THREAD

**Issue by jpuncle** [sindresorhus/gulp-markdown#12]
Env:
* node@10.1.0
* npm@6.1.0
* Mac

**Comment by awei01** [comment]
I ran into the same issue and did some deep digging. Turns out that this package is fine. It's the underlying package: `vinyl`. If you list your npm dependencies, you'll likely see that there are more than one version for `vinyl` being used, one of them being `< v1.0` which doesn't do anything when you to set `.extename`

To fix the issue, I pasted the following in my `package.json`:

```
  "dependencies": {
       // bunch of crap
   },
   // start here
  "resolutions": {
    "vinyl": "1.2.0"
  }
  // end here

```

then `npm install` and it should clear it up for you. 

@sindresorhus: not sure if it warrants an update to your `package.json` to create a `peerDependencies` entry for `vinyl` or not?
